version: "3.7"

services:
  gitlab-loukoum:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: ${VIRTUAL_HOST}
    ports:
      - '3080:80'
      - '3443:443'
      - '3022:22'
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - GITLAB_HOST=${VIRTUAL_HOST}
      - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
    networks:
      - default

networks:
  default:
    external:
      name: webproxy